compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

packageExtensions:
  odhin-reports-playwright@*:
    dependencies:
      postcss: ^8.4.49
  "@hmcts/playwright-common@*":
    dependencies:
      "@typescript-eslint/parser": ^8.8.0
