# https://github.com/yarnpkg/berry/issues/6247
# Due to a bug with yarn v4 and node>20.12, yarn v3 is used
# https://github.com/hmcts/cnp-jenkins-library/blob/master/resources/uk/gov/hmcts/pipeline/yarn/format-v4-audit.js
# The above file does not work with the ESM format, thus using yarn v3 to bypass
yarnPath: .yarn/releases/yarn-3.8.6.cjs
