compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.4.cjs

packageExtensions:
  odhin-reports-playwright@*:
    dependencies:
      postcss: ^8.4.49
